export enum EventLogging {
  EVL_FEED_INIT = 'ENQ_EVL_FEED_JOB_INITIATED',
  EVL_FEED_SUCCESS = 'ENQ_EVL_FEED_JOB_SUCCESS',
  EVL_FEED_FAILURE = 'ENQ_EVL_FEED_JOB_FAILED',

  TFL_FEED_INIT = 'ENQ_TFL_FEED_JOB_INITIATED',
  TFL_FEED_SUCCESS = 'ENQ_TFL_FEED_JOB_SUCCESS',
  TFL_FEED_FAILURE = 'ENQ_TFL_FEED_JOB_FAILED',

  ANTS_FEED_INIT = 'ENQ_ANTS_FEED_JOB_INITIATED',
  ANTS_FEED_SUCCESS = 'ENQ_ANTS_FEED_JOB_SUCCESS',
  ANTS_FEED_FAILURE = 'ENQ_ANTS_FEED_JOB_FAILED'
}
