import { TEST_RECORD_BY_VIN, TEST_RECORD_BY_VRM, TEST_RECORD_BY_TEST_NUMBER } from './testRecordQuery';
import TEST_DEFECT_QUERY from './testDefectQuery';
import CUSTOM_DEFECT_QUERY from './customDefectQuery';

export {
  TEST_RECORD_BY_VIN, TEST_RECORD_BY_VRM, TEST_RECORD_BY_TEST_NUMBER, TEST_DEFECT_QUERY, CUSTOM_DEFECT_QUERY,
};
