const VEHICLE_DETAILS_VRM_QUERY = 'SELECT * FROM *';
const VEHICLE_DETAILS_VIN_QUERY = 'SELECT * FROM *';
const VEHICLE_DETAILS_TRAILER_ID_QUERY = 'SELECT * FROM *';
const RESULTS_QUERY = 'SELECT * FROM *';

export {
  VEHICLE_DETAILS_VRM_QUERY, VEHICLE_DETAILS_VIN_QUERY, VEHICLE_DETAILS_TRAILER_ID_QUERY, RESULTS_QUERY,
};
