const VEHICLE_DETAILS_VRM_QUERY = 'SELECT * FROM `vehicle` WHERE `vrm_trm` = ?';
const VEHICLE_DETAILS_VIN_QUERY = 'SELECT * FROM `vehicle` WHERE `vin` = ?';
const VEHICLE_DETAILS_TRAILER_ID_QUERY = 'SELECT * FROM `vehicle` WHERE `trailer_id` = ?';
const RESULTS_QUERY = 'SELECT * FROM *';

export { VEHICLE_DETAILS_VRM_QUERY, VEHICLE_DETAILS_VIN_QUERY, VEHICLE_DETAILS_TRAILER_ID_QUERY, RESULTS_QUERY };
