name: CI
on:
  push:
    branches:
        - 'feature/CB2-8606'
  workflow_dispatch:
jobs:
  ci:
    uses: dvsa/cvs-github-actions/.github/workflows/node-ci.yaml@develop
    secrets:
      CVS_MGMT_AWS_ROLE: ${{ secrets.CVS_MGMT_AWS_ROLE }}
      CVS_SERVICES_S3: ${{ secrets.CVS_SERVICES_S3 }}
