name: PR-checks

on:
 push:
   branches: ['develop']
 pull_request:
   branches: ['develop']

jobs:
  scanner:
    permissions:
      id-token: write
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
      - name: Install dependencies
        run: npm ci
      - name: Build and Test
        uses: ./.github/workflows/build-and-test.yaml
      - name: Run SonarQube scanner
        run: |
         npm run test && \
         npm run sonar-scanner -- \
         -Dsonar.host.url=${{ secrets.SONARQUBE_GHA_URL }} \
         -Dsonar.token=${{ secrets.SONARQUBE_GHA_TOKEN }} \
         -Dsonar.login=${{ secrets.SONARQUBE_GHA_TOKEN }} \
         -Dsonar.projectName=${{ github.repository }} \
         -Dsonar.projectVersion=1.0.${{ github.run_id }}
